description: "This research project teaches **bros** how to make websites using GitHub Pages."
email: "bro@email.org"
twitter: "https://twitter.com/thewebbros"
team_members:
  - name: "Sarah Becker"
    role: "project lead"
    start_date: "2016-02-01"
  - name: "Jane Smith"
    role: maintainer
    start_date: "2018-03-15"
  - name: "Albert Hamilton"
    role: editor
    start_date: "2017-12-01"
