description: "This research project teaches **bros** how to make websites using GitHub Pages."
email: "bro@email.org"
twitter: "https://twitter.com/thewebbros"
collections:
  blogposts:
    output: true
team_members:
  -
    name: "Tom Cat"
    role: "project lead"
    start_date: "2020-10-01"
  -
    name: "Jane Smith"
    role: maintainer
    start_date: "2018-03-15"
  -
    name: "Albert Hamilton"
    role: editor
    start_date: "2017-12-01"
  -
    name: "Alice Dauncey"
    role: "developer"
    start_date: "2020-09-15"
